stages:
  convert-to-pdf:
    foreach:
    - simple_graphs
    do:
      cmd: >
        inkscape
        --without-gui
        --file=${item}.svg
        --export-pdf=${item}.pdf
        --export-latex
      deps:
      - ${item}.svg
      outs:
      - ${item}.pdf:
          cache: false
      - ${item}.pdf_tex:
          cache: false