stages:
  convert-to-pdf:
    foreach:
    - simple_graphs
    - simple-prevalences
    do:
      cmd: >
        inkscape
        --without-gui
        --file=${item}.svg
        --export-pdf=${item}.pdf
        --export-latex
      deps:
      - ${item}.svg
      outs:
      - ${item}.pdf:
          cache: false
      - ${item}.pdf_tex:
          cache: false

  simple-prevalences:
    cmd: python simple-prevalences.py
    deps:
    - ../data/simple-IIItoII-v1-prevalences.hdf5
    - ../data/simple-IItoIII-v1-prevalences.hdf5
    - ../data/simple-both-v1-prevalences.hdf5
    - ../data/simple-nocon-v1-prevalences.hdf5
    - simple-prevalences.py
    outs:
    - simple-prevalences.svg

  simple-corners:
    cmd: python simple-corner.py
    deps:
    - simple-corner.py
    - ../data/simple-both-v1-samples.hdf5
    - ../data/simple-nocon-v1-samples.hdf5
    outs:
    - simple-nocon-corner.svg
    - simple-both-corner.svg
