stages:
  plot-ipsi-prevalences:
    cmd: python prevalences_ipsi.py
    outs:
    - ipsi-comp.png
    - ipsi-comp.svg
    deps:
    - ../data/bilateral-v2-prevalences.hdf5
    - ../data/midline-with-mixing-v2-prevalences.hdf5
    - ../data/midline-without-mixing-v2-prevalences.hdf5
    - prevalences_ipsi.py
  ipsi-prevalences-to-pdf:
    cmd: inkscape --without-gui --file=ipsi-comp.svg --export-pdf=ipsi-comp.pdf --export-latex
    deps:
    - ipsi-comp.svg
    outs:
    - ipsi-comp.pdf
    - ipsi-comp.pdf_tex
  plot-contra-prevalences:
    cmd: python prevalences_contra.py
    deps:
    - ../data/bilateral-v2-prevalences.hdf5
    - ../data/midline-with-mixing-v2-prevalences.hdf5
    - ../data/midline-without-mixing-v2-prevalences.hdf5
    - prevalences_contra.py
    outs:
    - contra-comp.png
    - contra-comp.svg
  contra-prevalences-to-pdf:
    cmd: inkscape --without-gui --file=contra-comp.svg --export-pdf=contra-comp.pdf --export-latex
    deps:
    - contra-comp.svg
    outs:
    - contra-comp.pdf
    - contra-comp.pdf_tex
  plot-thermo-int:
    cmd: >
      python -m lyscripts plot thermo_int
      ../data/bilateral-v2-accuracies.csv
      ../data/midline-with-mixing-v2-accuracies.csv
      ../data/midline-without-mixing-v2-accuracies.csv
      -o thermo_int
      --labels agnostic mixing full
      --mplstyle ../../../.mplstyle
    deps:
    - ../data/bilateral-v2-accuracies.csv
    - ../data/midline-with-mixing-v2-accuracies.csv
    - ../data/midline-without-mixing-v2-accuracies.csv
    outs:
    - thermo_int.svg
    - thermo_int.png
  thermo-int-to-pdf:
    cmd: inkscape --without-gui --file=thermo_int.svg --export-pdf=thermo_int.pdf --export-latex
    deps:
    - thermo_int.svg
    outs:
    - thermo_int.pdf
    - thermo_int.pdf_tex