stages:
  plot-thermo-int:
    cmd: >
      python -m lyscripts plot thermo_int
      ../data/bilateral-v3-accuracies.csv
      ../data/midline-with-mixing-v3-accuracies.csv
      ../data/midline-without-mixing-v3-accuracies.csv
      -o thermo_int
      --labels agnostic mixing full
      --mplstyle ../../../.mplstyle
      && rm thermo_int.png
    deps:
    - ../data/bilateral-v3-accuracies.csv
    - ../data/midline-with-mixing-v3-accuracies.csv
    - ../data/midline-without-mixing-v3-accuracies.csv
    outs:
    - thermo_int.svg
  
  plot:
    foreach:
    - ipsi-overall
    - contra-overall
    - contra-correlations-ext
    - contra-correlations-noext
    - contra-risks
    do:
      cmd: python ${item}.py
      deps:
      - _utils.py
      - ${item}.py
      - ../data/bilateral-v3-prevalences.hdf5
      - ../data/midline-with-mixing-v3-prevalences.hdf5
      - ../data/midline-without-mixing-v3-prevalences.hdf5
      outs:
      - ${item}.svg
  
  convert-to-pdf:
    foreach:
    - ipsi-overall
    - contra-overall
    - contra-correlations-ext
    - contra-correlations-noext
    - thermo_int
    - contra-risks
    do:
      cmd: >
        inkscape
        --file=${item}.svg
        --export-pdf=${item}.pdf
        --without-gui
        --export-latex
      deps:
      - ${item}.svg
      outs:
      - ${item}.pdf:
          cache: false
      - ${item}.pdf_tex:
          cache: false
