stages:
  plot-ipsi-prevalences:
    cmd: python prevalences_ipsi.py
    outs:
    - ipsi-comp.png
    - ipsi-comp.svg
    deps:
    - prevalences_ipsi.py
  ipsi-prevalences-to-pdf:
    cmd: inkscape --without-gui --file=ipsi-comp.svg --export-pdf=ipsi-comp.pdf --export-latex
    deps:
    - ipsi-comp.svg
    outs:
    - ipsi-comp.pdf
    - ipsi-comp.pdf_tex
